export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const SYSTEM_CONFIG_REPOSITORY = Symbol('SYSTEM_CONFIG_REPOSITORY');
export const ACTIVITY_TAG_REPOSITORY = Symbol('ACTIVITY_TAG_REPOSITORY');
export const REFRESH_TOKEN_REPOSITORY = Symbol('REFRESH_TOKEN_REPOSITORY');
export const PASSWORD_SETUP_TOKEN_REPOSITORY = Symbol(
  'PASSWORD_SETUP_TOKEN_REPOSITORY',
);
